---
- hosts: dev
  become: True
  tasks:
    - name: starting docker container
      docker_container:
        name: mavenproject
        image: "devopstest777/mavenproject:{{DOCKER_TAG}}"
        state: started
        ports:
          - "8080:8080"
