---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: starting docker container
      community.docker.docker_container:
        name: mavenproject
        image: "devopstest777/mavenproject:{{DOCKER_TAG}}"
        state: started
        ports:
          - "8080:8080"
